name: kdtree
version: 0.2.0
description: A basic super fast Dart implementation of the k-dimensional (k-d) tree data structure.
homepage: https://github.com/JankoLancer/kd-tree-dart
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  pedantic: any
  test: any
