name: mbtiles
description: Mapbox MBTiles v1.3 files, support for vector and raster tiles.
version: 0.4.2
repository: https://github.com/josxha/dart_mbtiles
issue_tracker: https://github.com/josxha/dart_mbtiles/issues
topics: [ mbtiles, map ]
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  latlong2: ^0.9.0
  logging: ^1.2.0
  meta: ^1.10.0
  sqflite: ^2.0.0+4
  archive: any
  path: any
dev_dependencies:
  lint: ^2.2.0
  test: ^1.24.9