name: vector_tile
version: 2.0.0
description: >-
  A simple Dart package to encode & decode Mapbox Vector Tile, A implementation of Mapbox Vector Tile specification.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage: https://github.com/saigontek/dart-vector-tile
documentation: https://github.com/saigontek/dart-vector-tile
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  archive: ^3.6.1
  fixnum: ^1.0.0
  logging: ^1.2.0
  protobuf:
    path: ../protobuf.dart/protobuf
dev_dependencies:
  pedantic: ^1.0.0
